import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link, useLocation } from 'wouter';
import { Home, Users, BookOpen, Code, BarChart2, UserPlus, IndianRupee, PhoneCall, GraduationCap } from 'lucide-react';
import { cn } from '../../lib/utils';
import { useAuth } from '../../lib/simplified-auth';
export default function MobileNav() {
    const [location] = useLocation();
    const { user } = useAuth();
    const isActive = (path) => {
        return location === path;
    };
    const isManager = user?.role === 'manager' || user?.role === 'admin';
    return (_jsx("div", { className: "md:hidden fixed bottom-0 w-full border-t border-neutral-200 bg-white", children: _jsxs("div", { className: cn(isManager ? "grid-cols-8" : "grid-cols-5", "grid"), children: [_jsxs(Link, { href: "/", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(Home, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Home" })] }), _jsxs(Link, { href: "/batches", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/batches') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(Users, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Batches" })] }), _jsxs(Link, { href: "/courses", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/courses') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(BookOpen, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Courses" })] }), isManager && (_jsxs(_Fragment, { children: [_jsxs(Link, { href: "/leads", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/leads') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(PhoneCall, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Leads" })] }), _jsxs(Link, { href: "/students", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/students') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(UserPlus, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Students" })] }), _jsxs(Link, { href: "/fees", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/fees') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(IndianRupee, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Fees" })] }), _jsxs(Link, { href: "/trainers", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/trainers') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(GraduationCap, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Trainers" })] })] })), _jsxs(Link, { href: "/code-editor", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/code-editor') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(Code, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Code" })] }), _jsxs(Link, { href: "/analytics", className: cn("flex flex-col items-center pt-2 pb-1", isActive('/analytics') ? "text-primary-600" : "text-neutral-600 hover:text-primary-600"), children: [_jsx(BarChart2, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs", children: "Analytics" })] })] }) }));
}
//# sourceMappingURL=MobileNav.js.map